const fs=require('fs');
const path=require('path');
const APP='http://127.0.0.1:4173/bogatka-field-8f3c7d/?v=433';
const ARTIFACT_DIR=path.resolve('test-results/report-v433-review');
const BEFORE_FIXTURE=path.resolve('bogatka-field-8f3c7d/tests/fixtures/report-v433-before-pass.html');
async function openApp(page){
  await page.route('**/functions/v1/bogatka-version',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({version:'4.3.3',versionToken:'433',sourceCommit:'report433final',ahead:1})}));
  await page.addInitScript(()=>localStorage.setItem('bogatka_access_authorized_v1','1'));
  await page.goto(APP,{waitUntil:'networkidle'});
  await page.waitForFunction(()=>Boolean(window.BogatkaLiveReport?.build?.__reportFinalizeV433&&window.BogatkaLiveReport?.build?.__reportFinalizeV432&&typeof window.BogatkaReportFinalizeV433?.finalizeHtml==='function'&&typeof window.buildLocationReportHtml==='function'&&document.querySelector('[data-location-card]')),{timeout:45000});
}
async function seedFixtures(page){
  return page.evaluate(async()=>{
    const active=locations.filter(item=>!item.archivedAt),selected=active[0],second=active[1]||active[0],third=active[2]||second;
    const data=await getLocationData(selected.id);
    Object.assign(data,{decision:'Оставить',decisionReason:'Локация соответствует рабочему порогу по качеству, имеет приемлемую аренду и подтверждённый поток. Перед подписанием договора нужно зафиксировать условия ремонта и арендные каникулы.',status:'Осмотрено',objectType:'Торговое помещение',pros:'Подтверждённый поток, заметный фасад и приемлемая арендная нагрузка.',cons:'Ограниченная парковка в часы пик.',risks:'До подписания договора нужно письменно закрепить объём ремонта и арендные каникулы.',questions:'Получить финальную редакцию договора аренды.',tasks:[{id:'task-v433',title:'Получить проект договора и закрепить условия ремонта',status:'doing',priority:'high',createdAt:new Date().toISOString()}],score:{housing:4,occupied:4,foot:4,car:3,parking:4,stop:4,anchor:3,visibility:4,sign:3,loading:3,condition:4,storage:3,competition:3,overall:4},tech:{totalArea:'80',rentPerMonth:'3000',utilities:'400',repairEstimate:'12000',equipmentEstimate:'8000',deposit:'3000',powerKw:'15'},economy:{monthlyRevenue:'60000',grossMarginPct:'38',taxRatePct:'5',payroll:'5000',marketing:'900',logistics:'700',otherOpex:'600',initialStock:'20000',workingCapital:'6000',forecastNote:'Прогноз построен по сопоставимой действующей точке.'},trafficMeasurements:[{date:'2026-07-09',startTime:'10:00',peopleCount:'144',targetCustomers:'28',comment:'Стабильный поток в утренний период, заметная доля целевой аудитории.'}],competitors:[{name:'Конкурент рядом',distance:'150 м',prices:'сопоставимые',strengths:'видимость',weaknesses:'ограниченная парковка'}]});
    await idbPut(STORE,data,`location:${selected.id}`);
    const svg='<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="900"><rect width="1200" height="900" fill="#d7ddd8"/><rect x="90" y="130" width="1020" height="600" rx="28" fill="#f7f4eb"/><rect x="150" y="210" width="410" height="390" fill="#264f3d"/><rect x="610" y="210" width="430" height="390" fill="#b69055"/><text x="150" y="680" font-family="Arial" font-size="42" fill="#183a2b">Фотофиксация фасада</text></svg>';
    await idbPut(PHOTO_STORE,{id:'report-v433-lead',locationId:selected.id,category:'facade',caption:'Фотофиксация фасада',originalName:'facade.svg',width:1200,height:900,size:svg.length,createdAt:new Date().toISOString(),blob:new Blob([svg],{type:'image/svg+xml'})});
    if(second&&second.id!==selected.id){const d=await getLocationData(second.id);Object.assign(d,{decision:'Уточнить',decisionReason:'Требуется подтвердить трафик и условия аренды.',status:'На проверке',score:{housing:3,occupied:3,foot:2,car:3,parking:2,stop:3,anchor:2,visibility:3,sign:2,loading:2,condition:3,storage:2,competition:2,overall:3},tech:{totalArea:'72',rentPerMonth:'3400'},economy:{monthlyRevenue:'42000',grossMarginPct:'35',taxRatePct:'5',payroll:'4800',initialStock:'16000'},risks:'Трафик пока подтверждён только одним замером.'});await idbPut(STORE,d,`location:${second.id}`)}
    if(third&&third.id!==selected.id&&third.id!==second.id){const d=await getLocationData(third.id);Object.assign(d,{decision:'',status:'',score:{},tech:{},economy:{},questions:'Провести первичный осмотр и замер трафика.'});await idbPut(STORE,d,`location:${third.id}`)}
    if(typeof updateSummary==='function')await updateSummary();
    return{selectedId:selected.id,single:await window.buildLocationReportHtml(selected.id),full:await window.BogatkaLiveReport.build()};
  });
}
async function pageFromHtml(context,html,{width=1440,height=1000,print=false}={}){const report=await context.newPage();await report.setViewportSize({width,height});await report.setContent(html,{waitUntil:'load'});if(print)await report.emulateMedia({media:'print'});return report}
function px(value){return Number.parseFloat(value||'0')}
async function visualSnapshot(report){
  return report.evaluate(()=>{
    const px=value=>Number.parseFloat(value||'0'),style=node=>node?getComputedStyle(node):null,hero=document.querySelector('.report-hero-v433'),executive=document.querySelector('.report-executive-decision-v433,.report-portfolio-summary-v433'),display=document.querySelector('.report-display-v433'),sectionTitle=document.querySelector('.report-section-heading-v433 h2,.report-section-label-v432 strong'),body=document.querySelector('.report-context-v433,.report-field strong'),caption=document.querySelector('.report-eyebrow-v433,.report-section-label-v432 small'),kpi=document.querySelector('.report-hero-metric-v433 strong,.report-portfolio-kpi-v433 strong'),firstSection=document.querySelector('.report-section-accordion-v432'),firstBody=firstSection?.querySelector(':scope>.report-accordion-body-v432'),fields=[...document.querySelectorAll('.report-field')].filter(node=>node.getClientRects().length);
    return{heroCount:document.querySelectorAll('.report-hero-v433').length,oldCover:document.querySelectorAll('.report-cover').length,duplicateLocationHeader:document.querySelectorAll('.report-single-location-v432>.report-location-header').length,executiveCount:document.querySelectorAll('.report-executive-decision-v433').length,decisionPrimary:document.querySelectorAll('.report-decision-primary-v433').length,decisionStrips:document.querySelectorAll('.report-decision-strip').length,decisionAccordions:[...document.querySelectorAll('.report-section-label-v432 strong')].filter(node=>node.textContent.trim()==='Решение').length,displaySize:px(style(display)?.fontSize),sectionSize:px(style(sectionTitle)?.fontSize),bodySize:px(style(body)?.fontSize),captionSize:px(style(caption)?.fontSize),kpiSize:px(style(kpi)?.fontSize),heroBottom:hero?.getBoundingClientRect().bottom||0,executiveTop:executive?.getBoundingClientRect().top||0,heroSummaryGap:hero&&executive?executive.getBoundingClientRect().top-hero.getBoundingClientRect().bottom:null,accordionPaddingTop:firstBody?px(style(firstBody).paddingTop):0,accordionPaddingBottom:firstBody?px(style(firstBody).paddingBottom):0,fieldShadows:fields.map(node=>style(node).boxShadow),fieldRadii:fields.map(node=>px(style(node).borderRadius)),nestedAppBlocks:document.querySelectorAll('.report-location-card,.inspection-card-v416,.landlord-card-v416,.decision-panel-v412,.economy-v400,.traffic-stage7-v453,.launch-v455').length,rawDetails:document.querySelectorAll('details').length,controls:document.querySelectorAll('input,select,textarea').length,overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,generator:document.querySelector('meta[name="generator"]')?.content||''};
  });
}
module.exports={fs,path,ARTIFACT_DIR,BEFORE_FIXTURE,openApp,seedFixtures,pageFromHtml,visualSnapshot};
