(function(){
if(window.__bogatkaCompareV430)return;window.__bogatkaCompareV430=true;
const E=window.BogatkaDecisionEngine,VERSION='4.3.0',state={key:'rank',direction:'asc'},baseUpdateSummary=window.updateSummary||updateSummary;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,d=0)=>v===null||v===undefined||!Number.isFinite(Number(v))?'—':new Intl.NumberFormat('ru-RU',{maximumFractionDigits:d}).format(Number(v));
function setVersion(){const e=document.getElementById('versionLabel');if(e)e.textContent=VERSION}
function arrange(){const g=document.querySelector('.summary-grid');if(!g)return;g.classList.add('summary-grid-v332');['totalLocationsCount','completedCount','bestScore','averageScore','candidateCount','negotiationCount','keepCount','excludedCount','photoCount','storageUsage'].forEach(id=>{const m=document.getElementById(id)?.closest('.metric');if(m){m.classList.remove('wide');g.appendChild(m)}})}
function ensurePanel(){const card=document.querySelector('.summary.card'),grid=card?.querySelector('.summary-grid');if(!card||!grid)return null;let p=document.getElementById('locationComparisonPanel');if(p)return p;p=document.createElement('details');p.id='locationComparisonPanel';p.className='comparison-panel-v332 comparison-panel-v340';p.innerHTML=`<summary><span class="comparison-summary-copy"><strong>Таблица сравнения локаций</strong><small>Рейтинг, критические условия сделки, экономика, задачи и готовность к запуску</small></span><span class="comparison-count-v332" id="comparisonLocationCount">0 локаций</span><span class="comparison-chevron-v332"></span></summary><div class="comparison-body-v332"><div class="comparison-hint-v332">Нажмите на заголовок для сортировки. Нажмите на адрес, чтобы перейти к карточке.</div><div class="comparison-scroll-v332"><table class="comparison-table-v332 comparison-table-v340"><thead></thead><tbody></tbody><tfoot></tfoot></table></div></div>`;grid.insertAdjacentElement('afterend',p);p.addEventListener('toggle',()=>{if(p.open)render().catch(console.error)});return p}
function economy(m){return m.economy||window.BogatkaSuite?.calculateEconomy(m.data)||{}}
function openTasks(m){return(m.data.tasks||[]).filter(t=>t.status!=='done').length}
function launchProgress(m){const items=m.data.launchProject?.milestones||[];if(!items.length)return null;return Math.round(items.filter(i=>i.status==='done').length/items.length*100)}
function value(m,key){if(key==='title')return m.item.title||m.item.address||'';if(key==='status')return m.data.status||'';if(key==='objectType')return m.data.objectType||'';if(key==='decision')return m.data.decision||'';if(key==='recommendation')return m.recommendation.label;if(key==='dealGate')return m.dealGate.priority;if(key==='revenue')return economy(m).revenue;if(key==='profit')return economy(m).operatingProfit;if(key==='rentBurden')return economy(m).rentBurdenPct;if(key==='payback')return economy(m).paybackMonths;if(key==='tasks')return openTasks(m);if(key==='launch')return launchProgress(m);return m[key]}
function compare(a,b){let x=value(a,state.key),y=value(b,state.key);if(x===null||x===undefined||x==='')x=state.direction==='asc'?'\uffff':-Infinity;if(y===null||y===undefined||y==='')y=state.direction==='asc'?'\uffff':-Infinity;const r=typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y),'ru',{numeric:true,sensitivity:'base'});return state.direction==='asc'?r:-r}
function head(key,label){const active=state.key===key,arrow=active?(state.direction==='asc'?'▲':'▼'):'';return `<button type="button" data-compare-sort="${key}" class="${active?'active':''}">${esc(label)}<span>${arrow}</span></button>`}
function rec(m){return `<span class="compare-rec-v340 ${m.recommendation.className}">${esc(m.recommendation.label)}</span>`}
function deal(m){const tone=m.dealGate.code==='blocked'?'block':m.dealGate.code==='needs_formalization'?'risk':m.dealGate.code==='confirmed'?'clear':'empty';return `<span class="compare-stop-v340 ${tone}" title="${esc(m.dealGate.text)}">${esc(m.dealGate.compactText)}</span>`}
function mini(v){return v?`<span class="compare-mini-score-v332">${v}</span>`:'<span class="compare-empty-v332">—</span>'}
function row(m){const d=m.data,e=economy(m),launch=launchProgress(m),tasks=openTasks(m);return `<tr class="${m.dealGate.code==='blocked'?'compare-row-stop-v340':''}"><td class="compare-rank-v340"><strong>#${m.rank}</strong></td><td class="compare-location-v332"><button type="button" data-compare-location="${esc(m.id)}"><strong>${esc(m.item.title||m.item.address)}</strong>${m.item.address&&m.item.address!==m.item.title?`<small>${esc(m.item.address)}</small>`:''}</button></td><td>${rec(m)}</td><td>${deal(m)}</td><td class="compare-weight-v340"><strong>${fmt(m.weighted,1)}</strong><small>/100</small></td><td><span class="compare-complete-v340">${m.completion}%</span></td><td class="compare-score-total-v332"><strong>${m.rawScore}</strong><small>/70</small></td><td><span class="compare-status-v332">${esc(d.status||'Не выбран')}</span></td><td>${esc(d.objectType||'—')}</td><td>${fmt(m.area,1)}</td><td>${fmt(m.rent,2)}</td><td>${fmt(m.rentPerSqm,2)}</td><td>${fmt(e.revenue,2)}</td><td class="${e.operatingProfit<0?'compare-negative-v400':'compare-positive-v400'}">${fmt(e.operatingProfit,2)}</td><td>${e.rentBurdenPct==null?'—':`${fmt(e.rentBurdenPct,1)}%`}</td><td>${e.paybackMonths==null?'—':`${fmt(e.paybackMonths,1)} мес.`}</td><td>${mini(Number(d?.score?.foot)||0)}</td><td>${mini(Number(d?.score?.parking)||0)}</td><td>${mini(Number(d?.score?.competition)||0)}</td><td>${m.photoCount}</td><td>${tasks}</td><td>${launch==null?'—':`${launch}%`}</td><td>${esc(d.decision||'—')}</td></tr>`}
async function metrics(){return await E.computeAll()}
async function render(){const p=ensurePanel();if(!p)return;const table=p.querySelector('table'),rows=(await metrics()).sort(compare),count=p.querySelector('#comparisonLocationCount');if(count)count.textContent=`${rows.length} ${rows.length===1?'локация':rows.length>1&&rows.length<5?'локации':'локаций'}`;table.querySelector('thead').innerHTML=`<tr><th>${head('rank','Ранг')}</th><th>${head('title','Локация')}</th><th>${head('recommendation','Рекомендация')}</th><th>${head('dealGate','Условия сделки')}</th><th>${head('weighted','Вес /100')}</th><th>${head('completion','Заполнено')}</th><th>${head('rawScore','Балл /70')}</th><th>${head('status','Статус')}</th><th>${head('objectType','Тип')}</th><th>${head('area','Площадь')}</th><th>${head('rent','Аренда')}</th><th>${head('rentPerSqm','BYN/м²')}</th><th>${head('revenue','Выручка')}</th><th>${head('profit','Прибыль')}</th><th>${head('rentBurden','Аренда/%')}</th><th>${head('payback','Окупаемость')}</th><th>Поток</th><th>Парковка</th><th>Конкуренты</th><th>${head('photoCount','Фото')}</th><th>${head('tasks','Задачи')}</th><th>${head('launch','Запуск')}</th><th>${head('decision','Решение')}</th></tr>`;table.querySelector('tbody').innerHTML=rows.length?rows.map(row).join(''):'<tr><td colspan="23" class="comparison-empty-v332">Локаций пока нет.</td></tr>';const active=rows.filter(m=>m.completion>0),avgW=active.length?active.reduce((s,m)=>s+m.weighted,0)/active.length:0,avgC=active.length?active.reduce((s,m)=>s+m.completion,0)/active.length:0;table.querySelector('tfoot').innerHTML=`<tr><td colspan="4"><strong>Итого: ${rows.length} локаций</strong></td><td><strong>${fmt(avgW,1)}</strong></td><td><strong>${fmt(avgC,0)}%</strong></td><td colspan="13"></td><td><strong>${rows.reduce((s,m)=>s+m.photoCount,0)}</strong></td><td><strong>${rows.reduce((s,m)=>s+openTasks(m),0)}</strong></td><td colspan="2"></td></tr>`;table.querySelectorAll('[data-compare-sort]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.compareSort;if(state.key===k)state.direction=state.direction==='asc'?'desc':'asc';else{state.key=k;state.direction=['rank','dealGate','rent','rentPerSqm','rentBurden','payback','tasks'].includes(k)?'asc':'desc'}render().catch(console.error)}));table.querySelectorAll('[data-compare-location]').forEach(b=>b.addEventListener('click',()=>{const c=document.querySelector(`[data-location-card="${CSS.escape(b.dataset.compareLocation)}"]`);if(!c)return;c.scrollIntoView({behavior:'smooth',block:'start'});c.classList.add('compare-highlight-v332');setTimeout(()=>c.classList.remove('compare-highlight-v332'),1800)}))}
async function updateSummaryV430Compare(){if(baseUpdateSummary)await baseUpdateSummary();setVersion();arrange();ensurePanel();await render()}
window.updateSummary=updateSummaryV430Compare;try{updateSummary=updateSummaryV430Compare}catch(_){}setVersion();arrange();ensurePanel();render().catch(console.error);
})();
