(function(){
if(window.__bogatkaDecisionUIV340)return;window.__bogatkaDecisionUIV340=true;
const E=window.BogatkaDecisionEngine,DEAL=window.BogatkaCriticalDeal,SORT_KEY='bogatka_location_sort_v340';
const baseUpdateSummary=window.updateSummary||updateSummary;let refreshing=null,lastMetrics=[];const saveQueues=new Map();
const escHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setVersion(){window.BogatkaVersion?.apply?.()}
function ensureHeader(card,id){const head=card.querySelector('.location-head'),score=head?.querySelector('.scorebox');if(!head||!score||head.querySelector('.decision-head-v340'))return;const box=document.createElement('div');box.className='decision-head-v340';box.innerHTML=`<div class="decision-score-v340"><strong data-weighted-score="${id}">0</strong><small>/100</small><span>взвешенно</span></div><div class="decision-complete-v340"><strong data-completion-score="${id}">0%</strong><span>заполнено</span></div><span class="decision-recommendation-v340 empty" data-recommendation="${id}">Недостаточно данных</span>`;score.insertAdjacentElement('afterend',box);const wrap=head.querySelector('.location-title-wrap'),rank=wrap?.querySelector('.rank');if(rank&&!wrap.querySelector('[data-auto-rank]'))rank.insertAdjacentHTML('afterend',`<span class="auto-rank-v340" data-auto-rank="${id}"></span>`)}
function optionHtml(items){return items.map(item=>`<option value="${escHtml(item.value)}">${escHtml(item.label)}</option>`).join('')}
function conditionCard(id,definition){return `<article class="critical-condition-card-v430" data-critical-condition="${definition.key}"><div class="critical-condition-copy-v430"><strong>${escHtml(definition.title)}</strong><p class="critical-condition-help-v430" data-help="${escHtml(definition.help)}" aria-label="${escHtml(definition.help)}"></p></div><div class="critical-condition-controls-v430"><label class="field">Статус<select data-critical-location="${id}" data-critical-key="${definition.key}" data-critical-field="status">${optionHtml(DEAL.STATUSES)}</select></label><label class="field">${escHtml(definition.evidenceLabel||'Чем подтверждено')}<select data-critical-location="${id}" data-critical-key="${definition.key}" data-critical-field="evidenceType">${optionHtml(DEAL.evidenceOptions(definition))}</select></label><label class="field critical-condition-note-v430">Комментарий / что ещё нужно получить<textarea rows="3" data-critical-location="${id}" data-critical-key="${definition.key}" data-critical-field="note"></textarea></label></div><div class="critical-condition-error-v430" data-critical-error data-message="" aria-live="polite"></div></article>`}
function placeLeaseChecks(card,id,section){if(!section)return;const collaboration=card.querySelector(`[data-collaboration="${CSS.escape(id)}"]`);if(collaboration){if(collaboration.nextElementSibling!==section)collaboration.insertAdjacentElement('afterend',section);return}const decision=card.querySelector('.decision-panel-v412,.decision');if(decision){if(decision.previousElementSibling!==section)decision.insertAdjacentElement('beforebegin',section);return}const photos=[...card.querySelectorAll(':scope .location-body > details')].find(details=>details.querySelector(':scope > summary')?.textContent.includes('Фотографии'));if(photos&&photos.nextElementSibling!==section)photos.insertAdjacentElement('afterend',section)}
function buildSection(id){const section=document.createElement('details');section.className='critical-deal-v430';section.dataset.criticalDeal=id;section.dataset.schemaVersion=DEAL.VERSION;section.innerHTML=`<summary><span class="critical-summary-copy-v430"><strong>Проверки перед арендой</strong><small>Что нужно уточнить и получить от арендодателя перед авансом и подписанием договора.</small></span><span class="critical-summary-badge-v430" data-critical-summary="${id}">${DEAL.CONDITIONS.length} не проверено</span></summary><div class="details-body"><div class="critical-deal-gate-v430 incomplete" data-critical-gate="${id}">Проверки перед арендой пройдены не полностью</div><div class="critical-grid-v430">${DEAL.CONDITIONS.map(definition=>conditionCard(id,definition)).join('')}</div></div>`;bindConditionControls(section);return section}
function ensurePanels(card,id){const body=card.querySelector(':scope > .location-body');const anchor=body?.querySelector(':scope > .location-overview-v416')||body?.querySelector(':scope > .quick-grid')||body?.querySelector(':scope > .status-row');if(!body||!anchor)return;if(!card.querySelector(`[data-decision-overview="${id}"]`)){const o=document.createElement('div');o.className='decision-overview-v340';o.dataset.decisionOverview=id;o.innerHTML=`<div class="decision-overview-top-v340"><div><span>Взвешенная оценка</span><strong data-overview-weighted="${id}">0/100</strong></div><div><span>Полнота карточки</span><strong data-overview-completion="${id}">0%</strong></div><div><span>Проверки перед арендой</span><strong data-overview-stops="${id}">${DEAL.CONDITIONS.length} не проверено</strong></div><div><span>Рекомендация</span><strong data-overview-recommendation="${id}">Недостаточно данных</strong></div></div><div class="completion-track-v340"><span data-completion-bar="${id}"></span></div><div class="completion-missing-v340" data-completion-missing="${id}"></div><div class="decision-formula-v340">Вес показателей различается: 1 даёт 0% веса, 3 — 50%, 5 — 100%. Незаполненные оценки временно дают 0.</div>`;anchor.insertAdjacentElement('afterend',o)}
card.querySelector('.stop-factors-v340')?.remove();
let section=card.querySelector(`[data-critical-deal="${id}"]`);const invalidSection=section&&(section.dataset.schemaVersion!==DEAL.VERSION||section.querySelectorAll('[data-critical-condition]').length!==DEAL.CONDITIONS.length);if(invalidSection){section.remove();section=null}if(!section){section=buildSection(id);body.appendChild(section)}placeLeaseChecks(card,id,section)}
function actorId(){const actor=window.BogatkaSuite?.currentActor?.();return actor?.id||actor?.email||actor?.name||null}
function readConditionFromCard(card,key){return{status:card.querySelector(`[data-critical-key="${key}"][data-critical-field="status"]`)?.value||'unchecked',evidenceType:card.querySelector(`[data-critical-key="${key}"][data-critical-field="evidenceType"]`)?.value||'not_confirmed',note:card.querySelector(`[data-critical-key="${key}"][data-critical-field="note"]`)?.value||''}}
function localDataFromSection(section){const data={criticalDealConditions:{}};for(const definition of DEAL.CONDITIONS)data.criticalDealConditions[definition.key]=readConditionFromCard(section,definition.key);return data}
function renderSectionState(section,data){const gate=DEAL.evaluate(data);const id=section.dataset.criticalDeal;const badge=section.querySelector(`[data-critical-summary="${id}"]`);if(badge)badge.textContent=gate.badge;const result=section.querySelector(`[data-critical-gate="${id}"]`);if(result){result.textContent=gate.text;result.className=`critical-deal-gate-v430 ${gate.className}`}
for(const entry of gate.entries){const card=section.querySelector(`[data-critical-condition="${entry.definition.key}"]`);if(!card)continue;const error=card.querySelector('[data-critical-error]');const message=entry.validation.errors.join(' ');if(error)error.dataset.message=message;card.classList.toggle('critical-condition-invalid-v430',Boolean(message));card.querySelectorAll('select,textarea').forEach(control=>control.setAttribute('aria-invalid',message?'true':'false'))}return gate}
function queueSave(locationId,task){const previous=saveQueues.get(locationId)||Promise.resolve();const next=previous.catch(()=>{}).then(task);saveQueues.set(locationId,next);next.finally(()=>{if(saveQueues.get(locationId)===next)saveQueues.delete(locationId)});return next}
async function persistCondition(control,{refresh=true}={}){const section=control.closest('[data-critical-deal]');if(!section)return;const id=control.dataset.criticalLocation,key=control.dataset.criticalKey;const current=readConditionFromCard(section,key);if(current.status==='confirmed'&&DEAL.isOralEvidence(current.evidenceType)){current.status='needs_formalization';const status=section.querySelector(`[data-critical-key="${key}"][data-critical-field="status"]`);if(status)syncSelect(status,current.status)}renderSectionState(section,localDataFromSection(section));showSaving();await queueSave(id,async()=>{const data=await getLocationData(id);data.criticalDealConditions={...(data.criticalDealConditions||{})};const previous=DEAL.normalizeCondition(data.criticalDealConditions[key],key);data.criticalDealConditions[key]={...previous,...current,updatedAt:new Date().toISOString(),updatedBy:actorId()};data.updatedAt=new Date().toISOString();await idbPut(STORE,data,`location:${id}`);updateLocationTotal(id,data)});if(refresh)await updateSummary();showSaved()}
function bindConditionControls(section){section.querySelectorAll('select[data-critical-field]').forEach(control=>control.addEventListener('change',()=>persistCondition(control).catch(showError)));section.querySelectorAll('textarea[data-critical-field="note"]').forEach(control=>{control.addEventListener('input',()=>{renderSectionState(section,localDataFromSection(section));persistCondition(control,{refresh:false}).catch(showError)});control.addEventListener('blur',()=>updateSummary().catch(showError))})}
function syncSelect(select,value){if(select.value!==value)select.value=value;const trigger=select.nextElementSibling?.classList.contains('premium-select-trigger')?select.nextElementSibling:null;if(trigger&&typeof bogatkaSyncPremiumSelect==='function')bogatkaSyncPremiumSelect(select,trigger)}
function syncControl(control,value){if(!control)return;if(control===document.activeElement)return;if(control.tagName==='SELECT')syncSelect(control,value);else if(control.value!==value)control.value=value}
function text(card,selector,value){const element=card.querySelector(selector);if(element)element.textContent=value}
function updateCard(metric){const card=document.querySelector(`[data-location-card="${CSS.escape(metric.id)}"]`);if(!card)return;ensureHeader(card,metric.id);ensurePanels(card,metric.id);const weighted=Number.isInteger(metric.weighted)?metric.weighted:metric.weighted.toFixed(1);text(card,`[data-weighted-score="${metric.id}"]`,weighted);text(card,`[data-completion-score="${metric.id}"]`,`${metric.completion}%`);text(card,`[data-overview-weighted="${metric.id}"]`,`${weighted}/100`);text(card,`[data-overview-completion="${metric.id}"]`,`${metric.completion}%`);text(card,`[data-auto-rank="${metric.id}"]`,`Рейтинг #${metric.rank}`);text(card,`[data-overview-stops="${metric.id}"]`,metric.dealGate.compactText);text(card,`[data-overview-recommendation="${metric.id}"]`,metric.recommendation.label);const recommendation=card.querySelector(`[data-recommendation="${metric.id}"]`);if(recommendation){recommendation.textContent=metric.recommendation.label;recommendation.className=`decision-recommendation-v340 ${metric.recommendation.className}`;recommendation.title=metric.recommendation.reason}const bar=card.querySelector(`[data-completion-bar="${metric.id}"]`);if(bar)bar.style.width=`${metric.completion}%`;const missing=card.querySelector(`[data-completion-missing="${metric.id}"]`);if(missing)missing.innerHTML=metric.missing.length?`<strong>Ещё заполнить:</strong> ${metric.missing.slice(0,5).map(escHtml).join(' · ')}`:'<strong>Карточка заполнена.</strong> Можно принимать итоговое решение.';card.classList.toggle('has-stop-factor-v340',metric.dealGate.code==='blocked');card.classList.toggle('has-risk-factor-v340',metric.dealGate.code==='needs_formalization');const section=card.querySelector(`[data-critical-deal="${metric.id}"]`);if(section){placeLeaseChecks(card,metric.id,section);for(const definition of DEAL.CONDITIONS){const value=metric.criticalDealConditions[definition.key];syncControl(section.querySelector(`[data-critical-key="${definition.key}"][data-critical-field="status"]`),value.status);syncControl(section.querySelector(`[data-critical-key="${definition.key}"][data-critical-field="evidenceType"]`),value.evidenceType);syncControl(section.querySelector(`[data-critical-key="${definition.key}"][data-critical-field="note"]`),value.note)}renderSectionState(section,metric.data)}}
function ensureSort(){const root=document.getElementById('locations'),summary=document.querySelector('.summary.card');if(!root||!summary||document.getElementById('locationSortPanel'))return;const panel=document.createElement('section');panel.id='locationSortPanel';panel.className='location-sort-panel-v340';panel.innerHTML=`<div><strong>Порядок карточек</strong><span>Меняется только отображение, сохранённые адреса не затрагиваются.</span></div><label class="field">Сортировать<select id="locationSortMode"><option value="original">Исходный порядок</option><option value="rank">По автоматическому рейтингу</option><option value="weighted">По взвешенной оценке</option><option value="completion">По заполненности</option><option value="raw">По баллу из 70</option><option value="rent">По аренде: дешевле выше</option><option value="status">По статусу</option></select></label>`;summary.insertAdjacentElement('afterend',panel);const select=panel.querySelector('select');select.value=localStorage.getItem(SORT_KEY)||'original';select.addEventListener('change',()=>{localStorage.setItem(SORT_KEY,select.value);sortCards(lastMetrics,select.value)})}
function sortCards(metrics,mode){const root=document.getElementById('locations');if(!root||!metrics.length)return;const active=document.activeElement;if(active&&root.contains(active)&&active.matches('input,textarea,select,[contenteditable="true"]'))return;const items=[...metrics],order={'Кандидат':1,'Осмотрена':2,'Переговоры':3,'Оставить':4,'Исключить':5,'':9};if(mode==='rank')items.sort((a,b)=>a.rank-b.rank);else if(mode==='weighted')items.sort((a,b)=>b.weighted-a.weighted||b.completion-a.completion);else if(mode==='completion')items.sort((a,b)=>b.completion-a.completion||b.weighted-a.weighted);else if(mode==='raw')items.sort((a,b)=>b.rawScore-a.rawScore);else if(mode==='rent')items.sort((a,b)=>(a.rent??Infinity)-(b.rent??Infinity));else if(mode==='status')items.sort((a,b)=>(order[a.data.status||'']??8)-(order[b.data.status||'']??8)||a.rank-b.rank);else items.sort((a,b)=>a.originalIndex-b.originalIndex);const desired=items.map(metric=>metric.id),desiredSet=new Set(desired),current=[...root.querySelectorAll(':scope > [data-location-card]')].map(card=>card.dataset.locationCard).filter(id=>desiredSet.has(id));if(current.length===desired.length&&current.every((id,index)=>id===desired[index]))return;items.forEach(metric=>{const card=root.querySelector(`[data-location-card="${CSS.escape(metric.id)}"]`);if(card)root.appendChild(card)})}
async function refresh(){if(refreshing)return refreshing;refreshing=(async()=>{setVersion();ensureSort();lastMetrics=await E.computeAll();lastMetrics.forEach(updateCard);sortCards(lastMetrics,document.getElementById('locationSortMode')?.value||'original');return lastMetrics})().finally(()=>refreshing=null);return refreshing}
async function updateSummaryV340(){if(baseUpdateSummary)await baseUpdateSummary();await refresh()}
window.BogatkaDecisionUI={refresh,get lastMetrics(){return lastMetrics}};window.updateSummary=updateSummaryV340;try{updateSummary=updateSummaryV340}catch(_){}setVersion();refresh().catch(console.error);
})();
