(function(){
if(window.__bogatkaDecisionUIV340)return;window.__bogatkaDecisionUIV340=true;
const E=window.BogatkaDecisionEngine,VERSION=E.VERSION,SORT_KEY='bogatka_location_sort_v340';
const baseUpdateSummary=window.updateSummary||updateSummary;let refreshing=null,lastMetrics=[];
const escHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setVersion(){const e=document.getElementById('versionLabel');if(e)e.textContent=VERSION}
function ensureHeader(card,id){const head=card.querySelector('.location-head'),score=head?.querySelector('.scorebox');if(!head||!score||head.querySelector('.decision-head-v340'))return;const box=document.createElement('div');box.className='decision-head-v340';box.innerHTML=`<div class="decision-score-v340"><strong data-weighted-score="${id}">0</strong><small>/100</small><span>взвешенно</span></div><div class="decision-complete-v340"><strong data-completion-score="${id}">0%</strong><span>заполнено</span></div><span class="decision-recommendation-v340 empty" data-recommendation="${id}">Недостаточно данных</span>`;score.insertAdjacentElement('afterend',box);const wrap=head.querySelector('.location-title-wrap'),rank=wrap?.querySelector('.rank');if(rank&&!wrap.querySelector('[data-auto-rank]'))rank.insertAdjacentHTML('afterend',`<span class="auto-rank-v340" data-auto-rank="${id}"></span>`)}
function options(){return'<option value="">Не проверено</option><option value="clear">Нет проблемы</option><option value="risk">Есть риск / уточнить</option><option value="block">Есть стоп-фактор</option>'}
function ensurePanels(card,id){const q=card.querySelector('.quick-grid');if(!q)return;if(!card.querySelector(`[data-decision-overview="${id}"]`)){const o=document.createElement('div');o.className='decision-overview-v340';o.dataset.decisionOverview=id;o.innerHTML=`<div class="decision-overview-top-v340"><div><span>Взвешенная оценка</span><strong data-overview-weighted="${id}">0/100</strong></div><div><span>Полнота карточки</span><strong data-overview-completion="${id}">0%</strong></div><div><span>Стоп-факторы</span><strong data-overview-stops="${id}">не проверены</strong></div><div><span>Рекомендация</span><strong data-overview-recommendation="${id}">Недостаточно данных</strong></div></div><div class="completion-track-v340"><span data-completion-bar="${id}"></span></div><div class="completion-missing-v340" data-completion-missing="${id}"></div><div class="decision-formula-v340">Вес показателей различается: 1 даёт 0% веса, 3 — 50%, 5 — 100%. Незаполненные оценки временно дают 0.</div>`;q.insertAdjacentElement('afterend',o)}
if(!card.querySelector(`[data-stop-details="${id}"]`)){const d=document.createElement('details');d.className='stop-factors-v340';d.dataset.stopDetails=id;d.innerHTML=`<summary><span>Стоп-факторы</span><span class="stop-summary-badge-v340" data-stop-summary="${id}">не проверены</span></summary><div class="details-body"><p class="section-note">Условия, которые могут запретить открытие независимо от общего балла.</p><div class="stop-grid-v340">${E.STOPS.map(([k,l])=>`<div class="stop-row-v340"><strong>${escHtml(l)}</strong><select data-stop-location="${id}" data-stop-key="${k}">${options()}</select></div>`).join('')}</div></div>`;card.querySelector('.decision-overview-v340').insertAdjacentElement('afterend',d);d.querySelectorAll('[data-stop-key]').forEach(s=>s.addEventListener('change',()=>saveStop(s).catch(showError)))}}
async function saveStop(s){showSaving();const id=s.dataset.stopLocation,data=await getLocationData(id);data.stopFactors||={};data.stopFactors[s.dataset.stopKey]=s.value;data.updatedAt=new Date().toISOString();await idbPut(STORE,data,`location:${id}`);await updateSummary();showSaved()}
function syncSelect(s,v){if(s.value!==(v||''))s.value=v||'';const t=s.nextElementSibling?.classList.contains('premium-select-trigger')?s.nextElementSibling:null;if(t&&typeof bogatkaSyncPremiumSelect==='function')bogatkaSyncPremiumSelect(s,t)}
function text(card,sel,v){const e=card.querySelector(sel);if(e)e.textContent=v}
function updateCard(m){const card=document.querySelector(`[data-location-card="${CSS.escape(m.id)}"]`);if(!card)return;ensureHeader(card,m.id);ensurePanels(card,m.id);const w=Number.isInteger(m.weighted)?m.weighted:m.weighted.toFixed(1);text(card,`[data-weighted-score="${m.id}"]`,w);text(card,`[data-completion-score="${m.id}"]`,`${m.completion}%`);text(card,`[data-overview-weighted="${m.id}"]`,`${w}/100`);text(card,`[data-overview-completion="${m.id}"]`,`${m.completion}%`);text(card,`[data-auto-rank="${m.id}"]`,`Рейтинг #${m.rank}`);const stop=m.blocks?`${m.blocks} крит.`:m.risks?`${m.risks} требуют проверки`:m.stopAnswered===E.STOPS.length?'нет':`${E.STOPS.length-m.stopAnswered} не проверено`;text(card,`[data-overview-stops="${m.id}"]`,stop);text(card,`[data-stop-summary="${m.id}"]`,stop);text(card,`[data-overview-recommendation="${m.id}"]`,m.recommendation.label);const r=card.querySelector(`[data-recommendation="${m.id}"]`);if(r){r.textContent=m.recommendation.label;r.className=`decision-recommendation-v340 ${m.recommendation.className}`;r.title=m.recommendation.reason}const bar=card.querySelector(`[data-completion-bar="${m.id}"]`);if(bar)bar.style.width=`${m.completion}%`;const miss=card.querySelector(`[data-completion-missing="${m.id}"]`);if(miss)miss.innerHTML=m.missing.length?`<strong>Ещё заполнить:</strong> ${m.missing.slice(0,5).map(escHtml).join(' · ')}`:'<strong>Карточка заполнена.</strong> Можно принимать итоговое решение.';card.classList.toggle('has-stop-factor-v340',m.blocks>0);card.classList.toggle('has-risk-factor-v340',!m.blocks&&m.risks>0);E.STOPS.forEach(([k])=>{const s=card.querySelector(`[data-stop-key="${k}"]`);if(s)syncSelect(s,m.data?.stopFactors?.[k])})}
function ensureSort(){const root=document.getElementById('locations'),summary=document.querySelector('.summary.card');if(!root||!summary||document.getElementById('locationSortPanel'))return;const p=document.createElement('section');p.id='locationSortPanel';p.className='location-sort-panel-v340';p.innerHTML=`<div><strong>Порядок карточек</strong><span>Меняется только отображение, сохранённые адреса не затрагиваются.</span></div><label class="field">Сортировать<select id="locationSortMode"><option value="original">Исходный порядок</option><option value="rank">По автоматическому рейтингу</option><option value="weighted">По взвешенной оценке</option><option value="completion">По заполненности</option><option value="raw">По баллу из 70</option><option value="rent">По аренде: дешевле выше</option><option value="status">По статусу</option></select></label>`;summary.insertAdjacentElement('afterend',p);const s=p.querySelector('select');s.value=localStorage.getItem(SORT_KEY)||'original';s.addEventListener('change',()=>{localStorage.setItem(SORT_KEY,s.value);sortCards(lastMetrics,s.value)})}
function sortCards(metrics,mode){const root=document.getElementById('locations');if(!root||!metrics.length)return;const active=document.activeElement;if(active&&root.contains(active)&&active.matches('input,textarea,select,[contenteditable="true"]'))return;const a=[...metrics],so={'Кандидат':1,'Осмотрена':2,'Переговоры':3,'Оставить':4,'Исключить':5,'':9};if(mode==='rank')a.sort((x,y)=>x.rank-y.rank);else if(mode==='weighted')a.sort((x,y)=>y.weighted-x.weighted||y.completion-x.completion);else if(mode==='completion')a.sort((x,y)=>y.completion-x.completion||y.weighted-x.weighted);else if(mode==='raw')a.sort((x,y)=>y.rawScore-x.rawScore);else if(mode==='rent')a.sort((x,y)=>(x.rent??Infinity)-(y.rent??Infinity));else if(mode==='status')a.sort((x,y)=>(so[x.data.status||'']??8)-(so[y.data.status||'']??8)||x.rank-y.rank);else a.sort((x,y)=>x.originalIndex-y.originalIndex);const desired=a.map(m=>m.id);const desiredSet=new Set(desired);const current=[...root.querySelectorAll(':scope > [data-location-card]')].map(c=>c.dataset.locationCard).filter(id=>desiredSet.has(id));if(current.length===desired.length&&current.every((id,index)=>id===desired[index]))return;a.forEach(m=>{const c=root.querySelector(`[data-location-card="${CSS.escape(m.id)}"]`);if(c)root.appendChild(c)})}
async function refresh(){if(refreshing)return refreshing;refreshing=(async()=>{setVersion();ensureSort();lastMetrics=await E.computeAll();lastMetrics.forEach(updateCard);sortCards(lastMetrics,document.getElementById('locationSortMode')?.value||'original');return lastMetrics})().finally(()=>refreshing=null);return refreshing}
async function updateSummaryV340(){if(baseUpdateSummary)await baseUpdateSummary();await refresh()}
window.BogatkaDecisionUI={refresh,get lastMetrics(){return lastMetrics}};window.updateSummary=updateSummaryV340;try{updateSummary=updateSummaryV340}catch(_){ }setVersion();refresh().catch(console.error);
})();
