(function(){
if(window.__bogatkaWorkflowV350)return;window.__bogatkaWorkflowV350=true;
const VERSION='3.5.0';
const PHOTO_PLAN={street:3,entrance:3,parking:2,interior:5,engineering:2,competitors:2,documents:1};
const OPENING_STEPS=[['lease','Договор аренды'],['measure','Замер и планировка'],['design','Проект вывески/оформления'],['fire','Пожарные требования'],['repair','Ремонт'],['equipment','Оборудование'],['staff','Персонал'],['suppliers','Поставщики'],['goods','Первичная поставка'],['opening','Открытие']];
const ECON_FIELDS=[['area','Площадь, м²','number'],['rent','Аренда/мес, BYN','number'],['utilities','Коммунальные/экспл., BYN','number'],['payroll','ФОТ/мес, BYN','number'],['marketing','Маркетинг/мес, BYN','number'],['otherMonthly','Прочие расходы/мес, BYN','number'],['revenue','План выручки/мес, BYN','number'],['margin','Валовая маржа, %','number'],['deposit','Депозит, BYN','number'],['repair','Ремонт, BYN','number'],['equipment','Оборудование, BYN','number'],['inventory','Стартовый товар, BYN','number']];
let timer=null;
const escHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>{if(typeof v==='number')return Number.isFinite(v)?v:0;if(typeof v!=='string')return 0;const m=v.replace(/\s+/g,'').replace(',','.').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0])||0:0};
const money=v=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(Math.round(v||0));
function setVersion(){const e=document.getElementById('versionLabel');if(e)e.textContent=VERSION}
async function data(id){return await getLocationData(id)}
async function save(id,d){d.updatedAt=new Date().toISOString();await idbPut(STORE,d,`location:${id}`);await updateSummary();showSaved()}
function now(){return new Date().toLocaleString('ru-RU')}
async function addHistory(id,type,text){const d=await data(id);d.history||=[];d.history.unshift({id:crypto.randomUUID(),type,text,at:new Date().toISOString(),by:(await idbGet(STORE,'global'))?.inspector||'Пользователь'});d.history=d.history.slice(0,80);await idbPut(STORE,d,`location:${id}`)}
function ensureArchiveToggle(){if(document.getElementById('archiveTogglePanel'))return;const sort=document.getElementById('locationSortPanel'),summary=document.querySelector('.summary.card');const p=document.createElement('section');p.id='archiveTogglePanel';p.className='archive-toggle-v350';p.innerHTML='<label><input type="checkbox" id="showArchiveToggle"> Показывать архивные локации</label><span>Архив скрывает объект из рабочего списка, но сохраняет данные и фотографии.</span>';(sort||summary).insertAdjacentElement('afterend',p);p.querySelector('input').checked=localStorage.getItem('bogatka_show_archive')==='1';p.querySelector('input').addEventListener('change',e=>{localStorage.setItem('bogatka_show_archive',e.target.checked?'1':'0');applyArchiveVisibility()})}
function applyArchiveVisibility(){const show=localStorage.getItem('bogatka_show_archive')==='1';document.body.classList.toggle('show-archive-v350',show);document.querySelectorAll('[data-location-card]').forEach(async card=>{const d=await data(card.dataset.locationCard);card.classList.toggle('archived-location-v350',!!d.archived)})}
function normalizeAddress(v){return String(v||'').toLowerCase().replace(/ё/g,'е').replace(/город|гродно|ул\.?|улица|проспект|пр-т|тц|жк|[^а-яa-z0-9]+/g,' ').trim().replace(/\s+/g,' ')}
function findDuplicates(item){const n=normalizeAddress(item.address||item.title);if(!n)return[];return locations.filter(x=>x.id!==item.id&&normalizeAddress(x.address||x.title)===n)}
function ensureDuplicate(card,item){let box=card.querySelector('.duplicate-warning-v350');const dup=findDuplicates(item);if(!dup.length){box?.remove();return}if(!box){box=document.createElement('div');box.className='duplicate-warning-v350';card.querySelector('.location-actions')?.insertAdjacentElement('afterend',box)}box.innerHTML=`Возможный дубль адреса: ${dup.map(x=>`<b>${escHtml(x.title||x.address)}</b>`).join(', ')}.`}
function econHtml(id){return `<details class="workflow-panel-v350 economy-v350"><summary><span>Экономика и арендная нагрузка</span><span data-econ-badge="${id}">—</span></summary><div class="details-body"><div class="workflow-grid-v350">${ECON_FIELDS.map(([k,l,t])=>`<label class="field">${l}<input type="${t}" inputmode="decimal" data-econ-location="${id}" data-econ-key="${k}"></label>`).join('')}</div><div class="econ-results-v350" data-econ-results="${id}"></div></div></details>`}
function photoPlanHtml(id){return `<details class="workflow-panel-v350 photo-plan-v350"><summary><span>Обязательный фотоплан</span><span data-photo-plan-badge="${id}">0%</span></summary><div class="details-body"><div class="photo-plan-list-v350" data-photo-plan="${id}"></div></div></details>`}
function commentsHtml(id){return `<details class="workflow-panel-v350"><summary><span>Комментарии участников</span><span data-comments-badge="${id}">0</span></summary><div class="details-body"><textarea data-comment-text="${id}" placeholder="Комментарий по локации"></textarea><button class="btn small" data-add-comment="${id}" type="button">Добавить комментарий</button><div class="comment-list-v350" data-comments-list="${id}"></div></div></details>`}
function tasksHtml(id){return `<details class="workflow-panel-v350"><summary><span>Задачи по локации</span><span data-tasks-badge="${id}">0</span></summary><div class="details-body"><div class="task-form-v350"><input data-task-title="${id}" placeholder="Что нужно сделать"><input data-task-owner="${id}" placeholder="Ответственный"><input data-task-due="${id}" type="date"><button class="btn small" data-add-task="${id}" type="button">Добавить задачу</button></div><div class="task-list-v350" data-tasks-list="${id}"></div></div></details>`}
function openingHtml(id){return `<details class="workflow-panel-v350 opening-v350"><summary><span>Проект открытия магазина</span><span data-opening-badge="${id}">0%</span></summary><div class="details-body"><p class="section-note">Этот блок нужен после решения «Оставить»: помещение превращается в проект запуска точки.</p><div class="opening-list-v350" data-opening-list="${id}"></div></div></details>`}
function historyHtml(id){return `<details class="workflow-panel-v350 history-v350"><summary><span>История изменений</span><span data-history-badge="${id}">0</span></summary><div class="details-body"><div class="history-list-v350" data-history-list="${id}"></div></div></details>`}
function ensurePanels(card,item){const id=item.id;ensureDuplicate(card,item);if(card.querySelector(`[data-workflow-root="${id}"]`))return;const root=document.createElement('div');root.className='workflow-root-v350';root.dataset.workflowRoot=id;root.innerHTML=econHtml(id)+photoPlanHtml(id)+commentsHtml(id)+tasksHtml(id)+openingHtml(id)+historyHtml(id);const anchor=card.querySelector('.stop-factors-v340')||card.querySelector('.decision-overview-v340')||card.querySelector('.quick-grid');anchor?.insertAdjacentElement('afterend',root);bindPanel(root,id)}
function bindPanel(root,id){root.querySelectorAll('[data-econ-key]').forEach(i=>i.addEventListener('input',()=>{clearTimeout(i._t);i._t=setTimeout(()=>saveEcon(id).catch(showError),350)}));root.querySelector('[data-add-comment]')?.addEventListener('click',()=>addComment(id).catch(showError));root.querySelector('[data-add-task]')?.addEventListener('click',()=>addTask(id).catch(showError));root.addEventListener('change',e=>{const t=e.target;if(t.matches('[data-task-status]'))setTaskStatus(id,t.dataset.taskId,t.value).catch(showError);if(t.matches('[data-opening-step]'))setOpeningStep(id,t.dataset.step,t.value).catch(showError)})}
async function saveEcon(id){showSaving();const d=await data(id);d.economics||={};document.querySelectorAll(`[data-econ-location="${CSS.escape(id)}"]`).forEach(i=>{d.economics[i.dataset.econKey]=i.value});await addHistory(id,'economics','Обновлена экономика');await save(id,d)}
async function addComment(id){const input=document.querySelector(`[data-comment-text="${CSS.escape(id)}"]`);const text=input?.value.trim();if(!text)return;showSaving();const d=await data(id),g=await idbGet(STORE,'global')||{};d.comments||=[];d.comments.unshift({id:crypto.randomUUID(),text,by:g.inspector||'Пользователь',at:new Date().toISOString()});input.value='';await addHistory(id,'comment','Добавлен комментарий');await save(id,d)}
async function addTask(id){const title=document.querySelector(`[data-task-title="${CSS.escape(id)}"]`)?.value.trim();if(!title)return;const owner=document.querySelector(`[data-task-owner="${CSS.escape(id)}"]`)?.value.trim()||'';const due=document.querySelector(`[data-task-due="${CSS.escape(id)}"]`)?.value||'';showSaving();const d=await data(id);d.tasks||=[];d.tasks.unshift({id:crypto.randomUUID(),title,owner,due,status:'open',createdAt:new Date().toISOString()});document.querySelector(`[data-task-title="${CSS.escape(id)}"]`).value='';await addHistory(id,'task',`Добавлена задача: ${title}`);await save(id,d)}
async function setTaskStatus(id,taskId,status){showSaving();const d=await data(id);(d.tasks||[]).forEach(t=>{if(t.id===taskId)t.status=status});await addHistory(id,'task',`Изменён статус задачи: ${status}`);await save(id,d)}
async function setOpeningStep(id,step,status){showSaving();const d=await data(id);d.openingProject||={};d.openingProject[step]=status;await addHistory(id,'opening','Обновлён проект открытия');await save(id,d)}
async function toggleArchive(id){showSaving();const d=await data(id);d.archived=!d.archived;await addHistory(id,'archive',d.archived?'Локация отправлена в архив':'Локация возвращена из архива');await save(id,d);renderLocations();setTimeout(()=>refreshAll().catch(console.error),60)}
function ensureArchiveButton(card,id){const actions=card.querySelector('.location-actions');if(!actions||actions.querySelector(`[data-archive-location="${id}"]`))return;const b=document.createElement('button');b.type='button';b.className='btn secondary small';b.dataset.archiveLocation=id;b.textContent='В архив';b.addEventListener('click',()=>toggleArchive(id).catch(showError));actions.appendChild(b)}
function calcEcon(e){const area=num(e.area),rent=num(e.rent),utilities=num(e.utilities),payroll=num(e.payroll),marketing=num(e.marketing),other=num(e.otherMonthly),revenue=num(e.revenue),margin=num(e.margin),deposit=num(e.deposit),repair=num(e.repair),equipment=num(e.equipment),inventory=num(e.inventory);const fixed=rent+utilities+payroll+marketing+other;const rentLoad=revenue?(rent+utilities)/revenue*100:0;const breakeven=margin?fixed/(margin/100):0;const budget=deposit+repair+equipment+inventory;return{area,rent,utilities,payroll,marketing,other,revenue,margin,fixed,rentLoad,breakeven,budget,rentPerSqm:area?rent/area:0}}
async function updateCard(item){const id=item.id,card=document.querySelector(`[data-location-card="${CSS.escape(id)}"]`);if(!card)return;ensureArchiveButton(card,id);ensurePanels(card,item);const d=await data(id),e=d.economics||{};card.classList.toggle('archived-location-v350',!!d.archived);card.querySelector(`[data-archive-location="${id}"]`).textContent=d.archived?'Вернуть из архива':'В архив';document.querySelectorAll(`[data-econ-location="${CSS.escape(id)}"]`).forEach(i=>{if(i!==document.activeElement)i.value=e[i.dataset.econKey]||''});const c=calcEcon(e);const econ=card.querySelector(`[data-econ-results="${id}"]`);if(econ)econ.innerHTML=`<div><b>${money(c.rentPerSqm)}</b><span>BYN/м²</span></div><div><b>${c.rentLoad?c.rentLoad.toFixed(1):'0'}%</b><span>арендная нагрузка</span></div><div><b>${money(c.breakeven)}</b><span>точка безубыточности</span></div><div><b>${money(c.budget)}</b><span>стартовый бюджет</span></div>`;const badge=card.querySelector(`[data-econ-badge="${id}"]`);if(badge)badge.textContent=c.revenue?`${c.rentLoad.toFixed(1)}% нагрузки`:'не заполнено';await updatePhotoPlan(id,card);updateComments(id,card,d);updateTasks(id,card,d);updateOpening(id,card,d);updateHistory(id,card,d);}
async function updatePhotoPlan(id,card){const photos=(await idbAll(PHOTO_STORE)).filter(p=>p.locationId===id),list=card.querySelector(`[data-photo-plan="${id}"]`);if(!list)return;let done=0,total=0;list.innerHTML=Object.entries(PHOTO_PLAN).map(([cat,need])=>{const have=photos.filter(p=>(p.category||'other')===cat).length;done+=Math.min(have,need);total+=need;const title=(PHOTO_CATEGORIES.find(([k])=>k===cat)||[cat,cat])[1];return `<div class="photo-plan-row-v350 ${have>=need?'ok':''}"><span>${escHtml(title)}</span><b>${have}/${need}</b></div>`}).join('');const pct=total?Math.round(done/total*100):0;const badge=card.querySelector(`[data-photo-plan-badge="${id}"]`);if(badge)badge.textContent=`${pct}%`}
function updateComments(id,card,d){const a=d.comments||[],list=card.querySelector(`[data-comments-list="${id}"]`),badge=card.querySelector(`[data-comments-badge="${id}"]`);if(badge)badge.textContent=a.length;if(list)list.innerHTML=a.length?a.map(x=>`<div><b>${escHtml(x.by)}</b><small>${new Date(x.at).toLocaleString('ru-RU')}</small><p>${escHtml(x.text)}</p></div>`).join(''):'<p class="muted-v350">Комментариев пока нет.</p>'}
function updateTasks(id,card,d){const a=d.tasks||[],list=card.querySelector(`[data-tasks-list="${id}"]`),badge=card.querySelector(`[data-tasks-badge="${id}"]`);const open=a.filter(t=>t.status!=='done').length;if(badge)badge.textContent=open;if(list)list.innerHTML=a.length?a.map(t=>`<div class="task-row-v350 ${t.status==='done'?'done':''}"><div><b>${escHtml(t.title)}</b><small>${escHtml(t.owner||'без ответственного')} ${t.due?'· до '+escHtml(t.due):''}</small></div><select data-task-status data-task-id="${t.id}"><option value="open" ${t.status==='open'?'selected':''}>В работе</option><option value="waiting" ${t.status==='waiting'?'selected':''}>Ждём ответ</option><option value="done" ${t.status==='done'?'selected':''}>Готово</option></select></div>`).join(''):'<p class="muted-v350">Задач пока нет.</p>'}
function updateOpening(id,card,d){const project=d.openingProject||{},list=card.querySelector(`[data-opening-list="${id}"]`);if(!list)return;let done=0;list.innerHTML=OPENING_STEPS.map(([k,l])=>{const v=project[k]||'';if(v==='done')done++;return `<div class="opening-row-v350 ${v}"><span>${escHtml(l)}</span><select data-opening-step="${k}"><option value="" ${!v?'selected':''}>Не начато</option><option value="work" ${v==='work'?'selected':''}>В работе</option><option value="done" ${v==='done'?'selected':''}>Готово</option><option value="blocked" ${v==='blocked'?'selected':''}>Блокер</option></select></div>`}).join('');const pct=Math.round(done/OPENING_STEPS.length*100);const badge=card.querySelector(`[data-opening-badge="${id}"]`);if(badge)badge.textContent=`${pct}%`}
function updateHistory(id,card,d){const a=d.history||[],list=card.querySelector(`[data-history-list="${id}"]`),badge=card.querySelector(`[data-history-badge="${id}"]`);if(badge)badge.textContent=a.length;if(list)list.innerHTML=a.length?a.slice(0,20).map(h=>`<div><b>${escHtml(h.text)}</b><small>${new Date(h.at).toLocaleString('ru-RU')} · ${escHtml(h.by||'')}</small></div>`).join(''):'<p class="muted-v350">История появится после изменений.</p>'}
function bindGlobalHistory(){document.addEventListener('change',e=>{const el=e.target;if(!el.matches('[data-location][data-field]'))return;clearTimeout(el._hist);el._hist=setTimeout(()=>addHistory(el.dataset.location,'field',`Изменено поле: ${el.dataset.field}`).catch(console.error),450)},{capture:true})}
async function refreshAll(){setVersion();ensureArchiveToggle();for(const item of locations)await updateCard(item);applyArchiveVisibility()}
function observe(){const o=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>refreshAll().catch(console.error),80)});o.observe(document.body,{childList:true,subtree:true})}
window.BogatkaWorkflow={VERSION,refreshAll,PHOTO_PLAN,OPENING_STEPS};setVersion();bindGlobalHistory();refreshAll().catch(console.error);observe();
})();
